services:  
  orderserviceapi:
    image: orderserviceapi3
    build:
      context: .
      dockerfile: OrderMicroservice/Dockerfile
  productmicroservice:
    image: productmicroservice3
    build:
      context: .
      dockerfile: ProductMicroservice/Dockerfile
    ports:
      - 8082:8080