services:  
  orderserviceapi:
    image: orderserviceapi3
    build:
      context: .
      dockerfile: OrderMicroservice/Dockerfile
    ports:
      - 8080:8080
  productmicroservice:
    image: productmicroservice3
    build:
      context: .
      dockerfile: ProductMicroservice/Dockerfile
    ports:
      - 8081:8080
  authenticationapi:
    image: authenticationapi
    build:
      context: .
      dockerfile: AuthenticationAPI/Dockerfile
    ports:
      - 8082:8080
