version: '3.4'

services:
  ordermicroserviceapi:
    image: ${DOCKER_REGISTRY-}ordermicroserviceapi
    build:
      context: .
      dockerfile: OrderMicroservice/Dockerfile
    ports:
    - '65123:80'
  inventoryapi:
    image: ${DOCKER_REGISTRY-}inventoryapi
    build:
      context: .
      dockerfile: ../InventoryAPI/Dockerfile

