services:  
  orderserviceapi:
    image: orderserviceapi
    build:
      context: .
      dockerfile: OrderMicroservice/Dockerfile
    ports:
      - 8081:8080
  productmicroservice:
    image: productmicroservice
    build:
      context: .
      dockerfile: ProductMicroservice/Dockerfile
    ports:
      - 8082:8080